name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker image
      run: docker build . --file Dockerfile --tag  vikashkvikash/web-app:$(date +%s)
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: vikashkvikash/web-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

