name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
<<<<<<< HEAD

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: vikashkvikash/web-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
=======
    - name : docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      run : |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  vikashkvikash/web-app:$(date +%s)
    - name: docker push
      run: |
        docker push vikashkvikash/web-app
>>>>>>> 16032f2af8c7d7669f8d7683b1e9f6fabd237710

